name: Publish release

on:
  push:
  #  tags:
  #    - 'v*'

jobs:
  ig-publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Version tag only step
        run: |
          echo "Tag format is invalid"
          exit 1
        if: steps.version.outputs.is_valid != 'true'
    
      - uses: actions/checkout@v3

      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Install IG publisher
        run: |
          chmod +x ./_updatePublisher.sh
          ./_updatePublisher.sh -y

      - name: Build IG
        run: |
          chmod +x ./_genonce.sh
          ./_genonce.sh

      - name: Upload IG as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ig
          path: output/
          if-no-files-found: error
